baseURL = "https://davidfrancos.net"
languageCode = "es"
DefaultContentLanguage = "es"
title = "David Francos"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "David Francos"
author = "David Francos"
description = "Tecnología y patitos de goma"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params.math]
enable = false
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/davidfrancos/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/XayOn"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/david.francos"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@davidfrancos.net"

## Menu items

[menu]

  [[menu.main]]
  name = "Inicio"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Acerca de"
  weight = 300
  identifier = "about"
  url = "/about/"
